// Generates the integration material shown to the user after creating an agent.
//
// local agent → the user runs the code themselves (Claude Code CLI + claude
//               channel); we hand them ready-to-use source that implements the
//               three push APIs (heartbeat / metrics / logs).
// cloud agent → the same push client is baked into the runner that the manager
//               deploys to Cloudflare Sandbox (see templates in sandbox-worker).

export interface TemplateParams {
  agentId: string;
  agentName: string;
  apiToken: string;
  managerUrl: string;   // public URL of this API server
  queueName: string | null;
  instruction?: string | null;
}

// Shared push client — identical code is embedded in the cloud runner image.
export function pushClientSource(p: TemplateParams): string {
  return `// agent-push-client.js — auto-generated by agent-manager
// Implements the three push APIs every agent must call:
//   POST /internal/agents/:id/heartbeat   every 30s
//   POST /internal/agents/:id/metrics     every 60s
//   POST /internal/agents/:id/logs        batched, flushed every 5s
// Credentials come from .env — never hardcode AGENT_TOKEN in source.
const MANAGER_URL = process.env.AGENT_MANAGER_URL || ${JSON.stringify(p.managerUrl)};
const AGENT_ID    = process.env.AGENT_ID          || ${JSON.stringify(p.agentId)};
const AGENT_TOKEN = process.env.AGENT_TOKEN || "";
if (!AGENT_TOKEN) {
  console.error("[push] AGENT_TOKEN not set — copy the .env file from agent-manager");
  process.exit(1);
}

const HEADERS = { "Content-Type": "application/json", Authorization: "Bearer " + AGENT_TOKEN };
const base = () => MANAGER_URL.replace(/\\/$/, "") + "/internal/agents/" + AGENT_ID;

async function post(path, body) {
  try {
    const res = await fetch(base() + path, { method: "POST", headers: HEADERS, body: JSON.stringify(body) });
    if (!res.ok) console.error("[push] " + path + " → " + res.status);
  } catch (err) {
    console.error("[push] " + path + " failed:", err.message);
  }
}

export function sendHeartbeat(status = "running") {
  return post("/heartbeat", { status, uptimeSeconds: Math.floor(process.uptime()) });
}

export function sendMetrics(extra = {}) {
  const mem = process.memoryUsage();
  return post("/metrics", {
    memoryMb: Math.round(mem.rss / 1024 / 1024),
    uptimeSeconds: Math.floor(process.uptime()),
    ...extra,
  });
}

const logBuffer = [];
export function pushLog(message, level = "info", sessionId) {
  logBuffer.push({ message: String(message).slice(0, 10000), level, sessionId });
  if (logBuffer.length >= 100) flushLogs();
}
export async function flushLogs() {
  if (!logBuffer.length) return;
  const batch = logBuffer.splice(0, 100);
  await post("/logs", { logs: batch });
}

// start the loops
export function startReporting() {
  sendHeartbeat();
  setInterval(() => sendHeartbeat(), 30_000);
  setInterval(() => sendMetrics(), 60_000);
  setInterval(() => flushLogs(), 5_000);
  process.on("beforeExit", () => flushLogs());
}
`;
}

// Local runner: BullMQ consumer + Claude Code CLI + push client.
export function localRunnerSource(p: TemplateParams): string {
  const queueName = p.queueName ?? `broker-${p.agentId}`;
  return `// index.js — local agent runner, auto-generated by agent-manager
// Requires: npm install bullmq ioredis
// Env (.env): REDIS_URL, AGENT_MANAGER_URL, AGENT_ID, AGENT_TOKEN
import { spawn } from "node:child_process";
import { Worker } from "bullmq";
import IORedis from "ioredis";
import { startReporting, pushLog, flushLogs } from "./agent-push-client.js";

const QUEUE_NAME = process.env.QUEUE_NAME || ${JSON.stringify(queueName)};
const REDIS_URL  = process.env.REDIS_URL  || "redis://localhost:6379";

const SYSTEM_PROMPT = ${JSON.stringify(p.instruction || `# ${p.agentName}\n\nAgent system prompt.`)};

function runClaudeCLI(prompt) {
  return new Promise((resolveP, rejectP) => {
    const proc = spawn("claude", ["--print", "--output-format", "text"], {
      stdio: ["pipe", "pipe", "pipe"],
    });
    proc.stdin.write(prompt); proc.stdin.end();
    let out = "", err = "";
    proc.stdout.on("data", (d) => { out += d; });
    proc.stderr.on("data", (d) => { err += d; });
    proc.on("close", (code) => code !== 0 ? rejectP(new Error("claude exited " + code + ": " + err)) : resolveP(out.trim()));
    proc.on("error", rejectP);
  });
}

startReporting();
pushLog("agent runner started — queue: " + QUEUE_NAME);

const connection = new IORedis(REDIS_URL, { maxRetriesPerRequest: null });
new Worker(QUEUE_NAME, async (job) => {
  const text = String(job.data?.payload?.text ?? job.data?.text ?? JSON.stringify(job.data));
  pushLog("job " + job.id + " received: " + text.slice(0, 200));
  try {
    const reply = await runClaudeCLI(SYSTEM_PROMPT + "\\n\\n---\\n\\n" + text);
    pushLog("job " + job.id + " done: " + reply.slice(0, 200));
    return { reply };
  } catch (err) {
    pushLog("job " + job.id + " failed: " + err.message, "error");
    throw err;
  }
}, { connection, concurrency: Number(process.env.CONCURRENCY) || 1 });

process.on("SIGTERM", async () => { await flushLogs(); process.exit(0); });
`;
}

export function localEnvSource(p: TemplateParams): string {
  return [
    `# Agent: ${p.agentName}`,
    `AGENT_ID=${p.agentId}`,
    `AGENT_TOKEN=${p.apiToken}`,
    `AGENT_MANAGER_URL=${p.managerUrl}`,
    ``,
    `REDIS_URL=redis://localhost:6379`,
    `QUEUE_NAME=${p.queueName ?? `broker-${p.agentId}`}`,
    `CONCURRENCY=1`,
  ].join("\n");
}

// Minimal curl snippet shown inline in the UI.
export function heartbeatSnippet(p: TemplateParams): string {
  return [
    `# 每 30 秒打一次，agent-manager 會把這個 agent 標為 online`,
    `curl -X POST ${p.managerUrl}/internal/agents/${p.agentId}/heartbeat \\`,
    `  -H "Authorization: Bearer ${p.apiToken}" \\`,
    `  -H "Content-Type: application/json" \\`,
    `  -d '{"status":"running","uptimeSeconds":123}'`,
  ].join("\n");
}

export interface Integration {
  agentId: string;
  apiToken: string;
  managerUrl: string;
  endpoints: { heartbeat: string; metrics: string; logs: string };
  snippet: string;
  files: Record<string, string>; // filename → content, downloadable from UI
}

export function buildLocalIntegration(p: TemplateParams): Integration {
  const base = `${p.managerUrl}/internal/agents/${p.agentId}`;
  return {
    agentId: p.agentId,
    apiToken: p.apiToken,
    managerUrl: p.managerUrl,
    endpoints: {
      heartbeat: `${base}/heartbeat`,
      metrics: `${base}/metrics`,
      logs: `${base}/logs`,
    },
    snippet: heartbeatSnippet(p),
    files: {
      "agent-push-client.js": pushClientSource(p),
      "index.js": localRunnerSource(p),
      ".env": localEnvSource(p),
    },
  };
}
