// push-client.js — reports to agent-manager via the three push APIs.
// Identical contract to the local-agent template generated by the API:
//   POST /internal/agents/:id/heartbeat   every 30s
//   POST /internal/agents/:id/metrics     every 60s
//   POST /internal/agents/:id/logs        batched, flushed every 5s
const MANAGER_URL = process.env.AGENT_MANAGER_URL || "";
const AGENT_ID = process.env.AGENT_ID || "";
const AGENT_TOKEN = process.env.AGENT_TOKEN || "";

if (!MANAGER_URL || !AGENT_ID || !AGENT_TOKEN) {
  console.error("[push] AGENT_MANAGER_URL / AGENT_ID / AGENT_TOKEN must be set");
  process.exit(1);
}

const HEADERS = {
  "Content-Type": "application/json",
  Authorization: "Bearer " + AGENT_TOKEN,
};
const base = () => MANAGER_URL.replace(/\/$/, "") + "/internal/agents/" + AGENT_ID;

async function post(path, body) {
  try {
    const res = await fetch(base() + path, {
      method: "POST",
      headers: HEADERS,
      body: JSON.stringify(body),
    });
    if (!res.ok) console.error("[push] " + path + " → " + res.status);
  } catch (err) {
    console.error("[push] " + path + " failed:", err.message);
  }
}

export function sendHeartbeat(status = "running") {
  return post("/heartbeat", { status, uptimeSeconds: Math.floor(process.uptime()) });
}

export function sendMetrics(extra = {}) {
  const mem = process.memoryUsage();
  return post("/metrics", {
    memoryMb: Math.round(mem.rss / 1024 / 1024),
    uptimeSeconds: Math.floor(process.uptime()),
    ...extra,
  });
}

const logBuffer = [];
export function pushLog(message, level = "info", sessionId) {
  logBuffer.push({ message: String(message).slice(0, 10000), level, sessionId });
  if (logBuffer.length >= 100) flushLogs();
}

export async function flushLogs() {
  if (!logBuffer.length) return;
  const batch = logBuffer.splice(0, 100);
  await post("/logs", { logs: batch });
}

export function startReporting() {
  sendHeartbeat();
  setInterval(() => sendHeartbeat(), 30_000);
  setInterval(() => sendMetrics(), 60_000);
  setInterval(() => flushLogs(), 5_000);
  process.on("beforeExit", () => flushLogs());
}
